language: java
matrix:
  include:
    - name: "Linux JDK8 - R2js"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER=R2js
    - name: "Linux JDK8 - Renjin"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER=Renjin
    - name: "Linux JDK8 - Rserve"
      os: linux
      dist: trusty
      jdk:
        - openjdk8
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER="R://localhost"
    - name: "Linux JDK latest - R2js"
      os: linux
      dist: trusty
      jdk:
        - openjdk13
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER=R2js
    - name: "Linux JDK latest - Renjin"
      os: linux
      dist: trusty
      jdk:
        - openjdk13
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER=Renjin
    - name: "Linux JDK latest - Rserve"
      os: linux
      dist: trusty
      jdk:
        - openjdk13
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        - NO_CALCULATORS=1
        - R_SERVER="R://localhost"
    - name: "Linux JDK8 Test R"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        #- NO_TEST_ISSUES=1
        #- NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk8
    - name: "Linux JDK8 Test python"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        #- NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk8
    - name: "Linux JDK8 Test bash"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        #- NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk8
    - name: "Linux JDK latest Test R"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        #- NO_TEST_ISSUES=1
        #- NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk13
    - name: "Linux JDK latest Test python"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        #- NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk13
    - name: "Linux JDK latest Test bash"
      os: linux
      dist: trusty
      env:
        - TRAVIS_DIST_NAME="trusty"
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        #- NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - openjdk13
#    - name: "Linux JDK11"
#      os: linux
#      dist: xenial
#      jdk:
#        - openjdk11
#      env:
#        - TRAVIS_DIST_NAME="xenial"
#        - NO_TEST_R=1
#        - NO_TEST_PYTHON=1
#        - NO_TEST_BASH=1
#        - NO_TEST_CMD=1
#    - name: "Linux JDK11 Test R,python,bash"
#      os: linux
#      dist: xenial
#      env:
#        - TRAVIS_DIST_NAME="xenial"
#        - NO_TEST_JAVA=1
#        - NO_TEST_CMD=1
#      jdk:
#        - openjdk11
#    - name: "MacOS JDK8" This one is too slow to finsih in less than 50 min
#      os: osx
#      osx_image: xcode9.3
#      env:
#        - NO_TEST_ISSUES=1
#        - NO_TEST_R=1
#        - NO_TEST_PYTHON=1
#        - NO_TEST_BASH=1
#        - NO_TEST_CMD=1
    - name: "MacOS JDK8 Test R"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        #- NO_TEST_ISSUES=1
        #- NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk8
    - name: "MacOS JDK8 Test python"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        #- NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk8
    - name: "MacOS JDK8 Test bash"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        #- NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk8
    - name: "MacOS JDK latest Test R"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        #- NO_TEST_ISSUES=1
        #- NO_TEST_R=1
        - NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk13
    - name: "MacOS JDK latest Test python"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        #- NO_TEST_PYTHON=1
        - NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk13        
    - name: "MacOS JDK latest bash"
      os: osx
      osx_image: xcode9.3
      env:
        - NO_TEST_JAVA=1
        - NO_TEST_ISSUES=1
        - NO_TEST_R=1
        - NO_TEST_PYTHON=1
        #- NO_TEST_BASH=1
        - NO_TEST_CMD=1
        #- NO_CALCULATORS=1
        - R_SERVER=R2js
      jdk:
        - oraclejdk13
#    - name: "MacOS JDK11"
#      os: osx
#      osx_image: xcode10.1
#      env:
#        - global: JAVA_OPTS=-Xmx4g
#    - name: "Windows" --- Not yet supported
#      os: windows
#      jdk:
#        - oraclejdk8
#        - oraclejdk11
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait brew update >/dev/null; brew install ant; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install ant -y; fi

install:
  - WD=$PWD
  - cd ..
  - git clone https://github.com/Funz/funz-profile
  - git clone https://github.com/Funz/funz-core
  - cd funz-core
  - ant dist
  - cd ..
  - cd $WD
  - ant dist-test # required by funz-calculator/dist-test
  - cd ..
  - git clone https://github.com/Funz/funz-calculator
  - cd funz-calculator
  - ant dist-test
  - cd ..
  - cd $WD

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; rm -rf '/usr/local/bin/f2py'; brew install r; fi
  - if [[ "$TRAVIS_OSX_IMAGE" == "xcode9.3" ]]; then brew uninstall --ignore-dependencies --force python; brew install python3; fi # to get python3 instead of 2 -> ok.py test working
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [[ "$TRAVIS_DIST_NAME" == "trusty" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty-cran35/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_DIST_NAME" == "xenial" ]]; then echo "deb https://cloud.r-project.org/bin/linux/ubuntu xenial/" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install r-recommended --allow-unauthenticated -y; fi
  - if [[ "$NO_TEST_PYTHON" != "1" ]]; then if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; pip3 install numpy; pip3 install py4j==0.10.8.1;  fi; if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3-numpy python3-pip; sudo pip3 install py4j==0.10.8.1; fi; fi
  - if [[ "$NO_TEST_R" != "1" ]]; then if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/lib/jvm/default-java $JAVA_HOME; fi; if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_112.jdk/Contents/Home; fi; sudo R CMD javareconf JAVA_HOME=$JAVA_HOME; sudo R -e "install.packages('rJava',repos = 'https://cloud.r-project.org')"; fi

script:
  - echo "R.server="$R_SERVER > Funz.conf
  - cd dist; echo "R.server="$R_SERVER > Funz.conf; cd ..
  - if [[ "$NO_TEST_JAVA" == "1" ]]; then travis_wait 40 ant test; else ant test; fi

after_success:
  - if [[ "$NO_TEST_JAVA" != "1" ]]; then ant coverage ; fi
  - if [[ "$NO_TEST_JAVA" != "1" ]]; then bash <(curl -s https://codecov.io/bash) ; fi

before_deploy:
  - ant clean dist
  - cd dist; zip -r ../funz-client.zip ./*
  - cd ..

deploy:
  provider: releases
  name: funz-client
  api_key:
    secure: HeT5LHGWXUoTAj2G3TF+86uY+JmUNZeh/UT2XYB8NLUIz3z4/K+6odBDl+OTBlKsxTPLyV4T/RqBd0dZFN4YfuLnW5Q20GvItv6squCxCIw1pzAtVv0nOREeqk5b+zy+zF9snIAM9dPG2YUp1sdfk3eX6y0cnIcsNARXTZpfJozzzfGfkWFemqpNvGyM/l9mYgYx3ScOFSr6OCXLlF5v1Vb2XLt43Lp3mASpi9n8q1TfGXQr7+Si2fvZgS0srp3w/adeuPdEn6gadLH9E33kAwc30nH901Nwu+zQDeJiKl14Hiy2xmNZc/pgddwUFdCR+j0aJ16kPbHuURNEUnXeBdwnJ9/+GG7UVJD50WXG4JrXF7nPVnkjjl3MgcXojREhPrHL3VyoTsvmPjCPNPeCERKo/qMkuM663vpYwJc7krjyQ+45YHM0R5Z+iGeN7mbY1qAoaGrybct3GPDHsmtTB70Hn1pLUWMeqop4XhF+UjJhFtZr7P+ALquBxCZl1UOwFz9t+8ZHnDa3Ti1k3/u0OcciAtj2c20F0xE7qD9DRP80qX13Y21EwGEfSv0N/2rLEKRgpBXEP/mKtY4InpSsDQqVqJhebJnMKfr66+g3SwSQjz26MN0KVvN8EmpQggBhWB/PyMo+DR6gyZDAGSQakv9bcycevR1I0gjeV+dXCbI=
  file_glob: true
  file: funz-client*.zip
  on:
    tags: true
    branch: master
  skip_cleanup: true
  overwrite: true
